### ISSUE TITLE
Als werkzoekende wil ik eerst kunnen filteren op categorie, zodat ik per categorie kan zoeken op vacatures

### ISSUE THREAD

**Issue by Yevojr** [MeesH1111/MAANDAG-SPEEDCOURSE-REPOSITORY#11]
Acceptatie criteria

- [x] Een overzicht met categorieën is zichtbaar op de pagina 
- [x] De geselecteerde blijft visueel aanwezig 
- [x] Er is een optie om categorieën te resetten 
- [x] Na het resetten moet de gebruiker geredirect worden naar de overzicht pagina 

DoD

- [x] Webapp werkt op mobiel
- [x] Geen bugs
- [x] Minstens WCAG-A toegankelijk
- [x] Semantische code
- [x] Comments regels om uitleg te geven
- [x] OWASP top 10

**Comment by nbjjans-pixel** [comment]
categories\index.blade.php alles wat hier in zit moet nog in slots en layouts gezet worden
