### ISSUE TITLE
Als werkgever wil ik een bedrijfspagina kunnen aanmaken op Open Hiring zodat ik mijn bedrijf kan tonen aan werkzoekenden

### ISSUE THREAD

**Issue by J-Hoogvliet** [MeesH1111/MAANDAG-SPEEDCOURSE-REPOSITORY#19]
## Acceptatie Criteria

- [ ] Aanmaken van bedrijfspagina met de volgende informatie:
- [ ] Bedrijfsnaam
- [ ] Locatie
- [ ] Logo
- [ ] Beschrijving
- [ ] Contact Informatie

- [ ] Mogelijke Vacatures kunnen tonen

## DoD
- [ ] Voldoet aan huistijl
- [ ] Webapp werkt op mobiel
- [ ] Geen bugs
- [ ] Minstens WCAG-A toegankelijk
- [ ] Semantische code
- [ ] Comments regels om uitleg te geven
- [ ] OWASP top 10

**Comment by SemvanOsch** [comment]
Alleen de link van de terug knop moet nog aangepast worden
