### ISSUE TITLE
Als gebruiker wil ik dat ik ten allertijden via het Open Hiring logo terug kan naar de Home pagina, zodat ik altijd terug kan naar Home

### ISSUE THREAD

**Issue by Yevojr** [MeesH1111/MAANDAG-SPEEDCOURSE-REPOSITORY#20]
Acceptatie criteria 

- [x] Het logo fungeert als link naar de home pagina

DoD

- [x] Webapp werkt op mobiel
- [x] Geen bugs
- [x] Minstens WCAG-A toegankelijk
- [x] Semantische code
- [x] Comments regels om uitleg te geven
- [x] OWASP top 10

**Comment by MeesH1111** [comment]
Werken met Layouts
