### ISSUE TITLE
Als werknemer wil ik de linkjes naar andere pagina’s in het drop down menu goed kunnen zien, zodat ik via daar kan navigeren in de app.

### ISSUE THREAD

**Issue by J-Hoogvliet** [MeesH1111/MAANDAG-SPEEDCOURSE-REPOSITORY#27]
Acceptatiecriteria:
- [x] De links moeten altijd zichtbaar zijn, maakt niet uit welke achtergrond er op de pagina is.

DoD:
- [x] Webapp werkt op mobiel
- [x] Geen bugs
- [x] Minstens WCAG-A toegankelijk
- [x] Semantische code
- [x] Comments regels om uitleg te geven
- [x] OWASP top 10

**Comment by MeesH1111** [comment]
Hij kan nog niet af zijn omdat er een aantal dingen zijn die je nog niet tot beschikking hebt, zoals verschillende linkjes. Pas als je dit hebt kan je weer verder.

**Comment by MeesH1111** [comment]
Het ziet er top uit. Alleen zijn de linkjes naar de pagina's er nog niet. DIT MOET NOG AANGEPAST WORDEN!!!
